#! /usr/bin/env python3

import subprocess
import csv
import sys
import getopt


# class for holding information about counties
class County:
    def __init__(self, row):
        self.county_date = row[0]
        self.county_name = row[1]
        self.county_state = row[2]
        self.county_fips = row[3]
        self.county_cases = row[4]
        self.county_deaths = row[5]    

def getCurrentStatsForCounty(countyName):
    
    with open("../covid-19-data/us-counties.csv") as csv_file:
        county_reader = csv.reader(csv_file,delimiter=',')

        final_row = []
        for row in county_reader:
            if row[1] == countyName[0] and row[2] == countyName[1]:
                final_row = row

        if len(final_row) == 0:
            print("For", countyName[0], ",", countyName[1])
            print("County-State combonation not found in data")
            sys.exit(1)
        return County(final_row)


def outputCounty(county):
    print("-------------------------------------------------------------")
    print("COUNTY: ", county.county_name)
    print("=============================================================")
    print("\t{0:<30}| {1:<30}".format("MOST RECENT DATE", county.county_date))
    print("\t{0:<30}| {1:<30}".format("STATE", county.county_state))
    print("\t{0:<30}| {1:<30}".format("FIPS", county.county_fips))
    print("\t{0:<30}| {1:<30}".format("CASES", county.county_cases))
    print("\t{0:<30}| {1:<30}".format("DEATHS", county.county_deaths))
    print("-------------------------------------------------------------")
    # TODO get ratio of reported cases to deaths


def outputHelp():
    print("USAGE")
    print("{0:<30}| {1:<30}".format("-u", "Updates data with a pull from GitHub"))
    print("{0:<30}| {1:<30}".format("-c [ARG]", "Searches for specific county. FORMAT(no spaces): county,state "))
    print("{0:<30}| {1:<30}".format("-t", "Send text messages"))
    print("{0:<30}| {1:<30}".format("-o", "Output saved list to console"))
    print("{0:<30}| {1:<30}".format("-h", "Help"))
    sys.exit(0)

# Main method
if __name__ == '__main__':
   
    regular_options = "houtc:"

    # TODO integrate state totals?
    counties = [["Larimer", "Colorado"],
            ["Denver", "Colorado"],
            ["Hamilton", "Ohio"]]

    county_list = []
    
    # create each couty object and add to list
    for county in counties:
        county_list.append(getCurrentStatsForCounty(county))

    try:
        options, remainder = getopt.getopt(sys.argv[1:], regular_options)
    except getopt.error as err:
        print("getopt() error")
        print("Argument Not Recognized, run with '-h' for usage")
        sys.exit(1)

    for opt in options:
        if opt[0] == "-h":
            outputHelp()
        if opt[0] == "-u":
            subprocess.call(["git", "-C", "../covid-19-data", "pull", "origin", "master"])
        elif opt[0] == "-t":
            print("\n===  [SENDING TEXT MESSAGES] ===")
            # TODO write in text updates
        elif opt[0] == "-c":
            print("Searching for county: ", opt[1])
            # split into usable list 
            single_county_search = opt[1].split(',')
            outputCounty(getCurrentStatsForCounty(single_county_search))

        elif opt[0] == "-o":
            for county in county_list:
                outputCounty(county)



